package com.ca.scan.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ca.scan.dao.Profile;
import com.ca.scan.dao.History;
import com.ca.scan.dao.DescHistory;

import com.ca.scan.dao.ProfileDao;
import com.ca.scan.dao.HistoryDao;
import com.ca.scan.dao.DescHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig profileDaoConfig;
    private final DaoConfig historyDaoConfig;
    private final DaoConfig descHistoryDaoConfig;

    private final ProfileDao profileDao;
    private final HistoryDao historyDao;
    private final DescHistoryDao descHistoryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        profileDaoConfig = daoConfigMap.get(ProfileDao.class).clone();
        profileDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        descHistoryDaoConfig = daoConfigMap.get(DescHistoryDao.class).clone();
        descHistoryDaoConfig.initIdentityScope(type);

        profileDao = new ProfileDao(profileDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);
        descHistoryDao = new DescHistoryDao(descHistoryDaoConfig, this);

        registerDao(Profile.class, profileDao);
        registerDao(History.class, historyDao);
        registerDao(DescHistory.class, descHistoryDao);
    }
    
    public void clear() {
        profileDaoConfig.getIdentityScope().clear();
        historyDaoConfig.getIdentityScope().clear();
        descHistoryDaoConfig.getIdentityScope().clear();
    }

    public ProfileDao getProfileDao() {
        return profileDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

    public DescHistoryDao getDescHistoryDao() {
        return descHistoryDao;
    }

}
