package com.ca.scan.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DESC_HISTORY.
 */
public class DescHistory {

    private Long id;

    public String getEmployeename() {
        return employeename;
    }

    public void setEmployeename(String employeename) {
        this.employeename = employeename;
    }

    /** Not-null value. */
    private String employeename;
    /** Not-null value. */
    private String department;
    private String employeeid;
    private String desc;

    public DescHistory() {
    }

    public DescHistory(Long id) {
        this.id = id;
    }

    public DescHistory(Long id, String employeename, String department, String employeeid, String desc) {
        this.id = id;
        this.employeename = employeename;
        this.department = department;
        this.employeeid = employeeid;
        this.desc = desc;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }



    /** Not-null value. */
    public String getDepartment() {
        return department;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDepartment(String department) {
        this.department = department;
    }

    public String getEmployeeid() {
        return employeeid;
    }

    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

}
