package com.ca.scan.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table PROFILE.
 */
public class Profile implements Serializable {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String department;
    private String employeeid;
    private java.util.Date date;

    public Profile() {
    }

    public Profile(Long id) {
        this.id = id;
    }

    public Profile(Long id, String name, String department, String employeeid, java.util.Date date) {
        this.id = id;
        this.name = name;
        this.department = department;
        this.employeeid = employeeid;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getDepartment() {
        return department;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDepartment(String department) {
        this.department = department;
    }

    public String getEmployeeid() {
        return employeeid;
    }

    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
