package com.ca.scan.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SCAN_HISTORY.
 */
public class ScanHistory {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String department;
    private String employeeid;
    /** Not-null value. */
    private String expressno;
    private String filename;
    private String ifupload;
    private String desc;
    private java.util.Date date;

    public ScanHistory() {
    }

    public ScanHistory(Long id) {
        this.id = id;
    }

    public ScanHistory(Long id, String name, String department, String employeeid, String expressno, String filename, String ifupload, String desc, java.util.Date date) {
        this.id = id;
        this.name = name;
        this.department = department;
        this.employeeid = employeeid;
        this.expressno = expressno;
        this.filename = filename;
        this.ifupload = ifupload;
        this.desc = desc;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getDepartment() {
        return department;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDepartment(String department) {
        this.department = department;
    }

    public String getEmployeeid() {
        return employeeid;
    }

    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }

    /** Not-null value. */
    public String getExpressno() {
        return expressno;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setExpressno(String expressno) {
        this.expressno = expressno;
    }

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public String getIfupload() {
        return ifupload;
    }

    public void setIfupload(String ifupload) {
        this.ifupload = ifupload;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
